blank_issues_enabled: false
contact_links:
  - name: Lire le mode d’emploi
    url: https://github.com/ortiz-luis/fluoxetine-france#utiliser-la-carte
    about: Comment appeler une pharmacie et partager une confirmation

